export default function Privacy() {
  return (
    <div className="flex flex-col items-center text-black overflow-y-auto p-8 pt-20">
      <h1 className="text-4xl mb-8">Privacy Policy</h1>
      <div className="prose max-w-3xl bg-white p-8 rounded-lg">
        <p><em>Updated: July 1, 2025</em></p>

<p>At our company, we prioritize your privacy and aim to collect the least amount of personal data from you as possible. We only collect information when necessary for the functionality of our website and apps. Whenever feasible, we provide you with the option to opt out of data collection. Further details regarding the data we collect and the reasons behind it are outlined in the following sections.</p>

<p>Snacks After Midnight (“us”, “we”, or “our”) operates the https://snacksaftermidnight.com website and the Chroma - Cinema For Plex application (“Chroma”, or the “Service”).</p>

<p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions.</p>

<h2 id="definitions">Definitions</h2>
<ul>
  <li><strong>Service.</strong> Service means the https://snacksaftermidnight.com website and/or the Chroma application operated by Snacks After Midnight</li>
  <li><strong>Personal Data.</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).</li>
  <li><strong>Usage Data.</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
  <li><strong>Cookies.</strong> Cookies are small pieces of data stored on your device (computer or mobile device).</li>
  <li><strong>Data Controller.</strong> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.</li>
  <li><strong>Data Processors</strong> (or Service Providers). Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.</li>
  <li><strong>Data Subject (or User).</strong> Data Subject is any living individual who is using our Service and is the subject of Personal Data.</li>
</ul>

<h2 id="information-collection-and-use">Information Collection And Use</h2>
<p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>

<h3 id="personal-data">Personal Data</h3>

<p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you (“Personal Data”). Personally identifiable information may include profile information such as your email address, username, a profile image, and password when you create an account, or when you edit your account information. You may also provide us with your payment information when you sign-up for a paid service.</p>

<p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send.</p>

<h3 id="usage-data">Usage Data</h3>
<p>We may also collect information that your browser sends whenever you visit our Service or when you access the Service by or through a mobile device (“Usage Data”).</p>

<p>This Usage Data may include information such as your computer’s browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>

<p>When you access the Service by or through a mobile device, this Usage Data may include information such as the type of mobile device you use, your mobile operating system, the type of mobile Internet browser you use, unique device identifiers and other diagnostic data.</p>

<h3 id="tracking--cookies-data">Tracking &amp; Cookies Data</h3>
<p>We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.</p>

<p>Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.</p>

<p>You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.</p>

<p>Examples of Cookies we use:</p>

<ul>
  <li>Session Cookies. We use Session Cookies to operate our Service.</li>
  <li>Preference Cookies. We use Preference Cookies to remember your preferences and various settings.</li>
  <li>Security Cookies. We use Security Cookies for security purposes.</li>
</ul>

<h2 id="use-of-data">Use of Data</h2>

<p>Snacks After Midnight uses the collected data for various purposes:</p>

<ul>
  <li>To provide and maintain our Service</li>
  <li>To notify you about changes to our Service</li>
  <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
  <li>To provide customer support</li>
  <li>To gather analysis or valuable information so that we can improve our Service</li>
  <li>To monitor the usage of our Service</li>
  <li>To detect, prevent and address technical issues</li>
  <li>To provide you with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
</ul>

<h2 id="legal-basis-for-processing-personal-data-under-general-data-protection-regulation-gdpr">Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h2>

<p>If you are from the European Economic Area (EEA), Snacks After Midnight legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.</p>

<p>Snacks After Midnight may process your Personal Data because:</p>

<ul>
  <li>We need to perform a contract with you</li>
  <li>You have given us permission to do so</li>
  <li>The processing is in our legitimate interests and it’s not overridden by your rights</li>
  <li>For payment processing purposes</li>
  <li>To comply with the law</li>
</ul>

<h2 id="retention-of-data">Retention of Data</h2>

<p>Snacks After Midnight will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>

<p>Snacks After Midnight will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

<h2 id="transfer-of-data">Transfer Of Data</h2>

<p>Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>

<p>If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.</p>

<p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.</p>

<p>Snacks After Midnight will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.</p>

<h2 id="disclosure-of-data">Disclosure Of Data</h2>

<h3 id="business-transaction">Business Transaction</h3>

<p>If Snacks After Midnight is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>

<h3 id="disclosure-for-law-enforcement">Disclosure for Law Enforcement</h3>

<p>Under certain circumstances, Snacks After Midnight may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>

<h3 id="legal-requirements">Legal Requirements</h3>

<p>Snacks After Midnight may disclose your Personal Data in the good faith belief that such action is necessary to:</p>

<ul>
  <li>To comply with a legal obligation</li>
  <li>To protect and defend the rights or property of Snacks After Midnight</li>
  <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
  <li>To protect the personal safety of users of the Service or the public</li>
  <li>To protect against legal liability</li>
</ul>

<h2 id="security-of-data">Security Of Data</h2>

<p>The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>

<h2 id="do-not-track-signals">“Do Not Track” Signals</h2>

<p>We support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.</p>

<p>You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.</p>

<h2 id="your-data-protection-rights-under-general-data-protection-regulation-gdpr">Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h2>

<p>If you are a resident of the European Economic Area (EEA), Snacks After Midnight aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.</p>

<p>If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.</p>

<p>In certain circumstances, you have the following data protection rights:</p>

<ul>
  <li><strong>The right to access, update or to delete the information we have on you.</strong> Whenever made possible, you can access, update or request deletion of your Personal Data directly within your account settings section. If you are unable to perform these actions yourself, please contact us to assist you.</li>
  <li><strong>The right of rectification.</strong> You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
  <li><strong>The right to object.</strong> You have the right to object to our processing of your Personal Data.</li>
  <li><strong>The right of restriction.</strong> You have the right to request that we restrict the processing of your personal information.</li>
  <li><strong>The right to data portability.</strong> You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
  <li><strong>The right to withdraw consent.</strong> You also have the right to withdraw your consent at any time where Snacks After Midnight relied on your consent to process your personal information.</li>
</ul>

<p>Please note that we may ask you to verify your identity before responding to such requests.</p>

<p>You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).</p>

<h2 id="service-providers">Service Providers</h2>

<p>We may employ third party companies and individuals to facilitate our Service (“Service Providers”), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.</p>

<p>These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.</p>

<h2 id="analytics">Analytics</h2>

<p>We may use third-party Service Providers to monitor and analyze the use of our Service.</p>

<ul>
  <li><strong>Google Analytics.</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network.</li>
</ul>

<p>For more information on the privacy practices of Google, please visit the Google Privacy &amp; Terms web page: http://www.google.com/intl/en/policies/privacy/</p>

<h2 id="payments">Payments</h2>

<p>We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g. payment processors).</p>

<p>We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.</p>

<p>The payment processors we work with are:</p>

<ul>
  <li><strong>Apple Store Payments.</strong> Their Privacy Policy can be viewed at https://www.apple.com/legal/privacy/en-ww/</li>
</ul>

<h2 id="links-to-other-sites">Links To Other Sites</h2>

<p>Our Service may contain links to other sites that are not operated by us. If you click on a third party link, you will be directed to that third party’s site. We strongly advise you to review the Privacy Policy of every site you visit.</p>

<p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

<h2 id="childrens-privacy">Children’s Privacy</h2>

<p>Our Service does not address anyone under the age of 18 (“Children”).</p>

<p>We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your Children has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.</p>

<h2 id="changes-to-this-privacy-policy">Changes To This Privacy Policy</h2>

<p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.</p>

<p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>

<h2 id="contact-us">Contact Us</h2>

<p>If you have any questions about this Privacy Policy, you can contact us via <a href="mailto:drew@snacksaftermidnight.com">email</a>.</p>
      </div>
    </div>
  );
}